version: 1

# update_schedule: live is only supported on javascript, ruby:bundler, python, php:composer, dotnet:nuget, rust:cargo, elixir:hex

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    ignored_updates:
      - match:
          dependency_name: "System.*"
      - match:
          dependency_name: "Microsoft.Win32.Registry.AccessControl"
      - match:
          dependency_name: "Microsoft.Windows.Compatibility"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    ignored_updates:
      - match:
          dependency_name: "System.*"
      - match:
          dependency_name: "Microsoft.Win32.Registry.AccessControl"
      - match:
          dependency_name: "Microsoft.Windows.Compatibility"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/System.Management.Automation"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    ignored_updates:
      - match:
          dependency_name: "System.*"
      - match:
          dependency_name: "Microsoft.Win32.Registry.AccessControl"
      - match:
          dependency_name: "Microsoft.Windows.Compatibility"

  - package_manager: "dotnet:nuget"
    directory: "/test/tools/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    ignored_updates:
      - match:
          dependency_name: "System.*"
      - match:
          dependency_name: "Microsoft.Win32.Registry.AccessControl"
      - match:
          dependency_name: "Microsoft.Windows.Compatibility"

  - package_manager: "dotnet:nuget"
    directory: "/src/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
