parameters:
  jobName: release
  imageName: windows-2019
  displayName: 'Release Microsoft.PowerShell.RemotingTools to NuGet'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - powershell: |
      Get-ChildItem '$(Build.ArtifactStagingDirectory)/nupkg/Microsoft.PowerShell.RemotingTools.*.nupkg'
    displayName: 'Capture NuGet package'

  - task: NuGetCommand@2
    displayName: 'Push PSThreadJob artifacts to AzArtifactsFeed'
    inputs:
      command: push
      packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.RemotingTools.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: AzArtifactFeed
