language: cpp
sudo: required
dist: trusty
git:
  submodules: false
before_install:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init
  - sudo apt-get install -y -qq curl make g++ cmake libc6 libgcc1 libstdc++6 libcurl3 libgssapi-krb5-2 libicu52 liblldb-3.6 liblttng-ust0 libssl1.0.0 libunwind8 libuuid1 zlib1g clang-3.5
  - curl -s "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh" -o dotnet-install.sh
  - bash ./dotnet-install.sh -c rel-1.0.0 -v latest
script:
  - ./build.sh
  - ./test.sh
