language: c

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.3

sudo: required

addons:
  apt:
    packages:
      - libpam0g-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - rpm
      - librpm-dev

script: make release
